# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [4]:
#Creating sample array
arr=np.arange(0,21)

In [5]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [7]:
#Creating sample array
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [8]:
len(arr)

18

In [9]:
arr[4]

30

In [10]:
#Get a value at an index
arr[9]

55

In [11]:
arr[1:11:2]

array([15, 25, 35, 45, 55])

In [14]:
#Get values in a range
s=np.array([6,3,2,7,1,4])
s


array([6, 3, 2, 7, 1, 4])

In [17]:
s[2:6]

array([2, 7, 1, 4])

In [18]:
s[2:]

array([2, 7, 1, 4])

### Filtering

In [19]:
import numpy as np

In [20]:
# Filtering condition 

arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [21]:
filterarr=arr<100
filterarr

array([ True,  True, False,  True, False,  True,  True, False])

In [22]:
nwarry=arr[arr<100]
nwarry

array([ 1,  2,  4, 18, 71])

In [23]:
arr[5]

18

In [11]:
np.where(arr>100) # where function outputs index location of values
# meeting the condition

(array([2, 4, 7], dtype=int64),)

In [11]:
np.where(arr<100)

(array([0, 1, 3, 5, 6], dtype=int64),)

In [13]:
np.where(arr==100) #no element with value 100

(array([], dtype=int64),)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [24]:
import numpy as np

In [25]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [26]:
arr_2d[2,2]

128

In [29]:
arr_2d[1,2]

18

In [30]:
arr_2d[:3,:2]

array([[ 1,  2],
       [12, 15],
       [64, 96]])

In [31]:
arr_2d.shape

(3, 3)

In [32]:
arr_2d[1]  # Indexing 2nd row

array([12, 15, 18])

In [33]:
arr_2d[:,2] # Indexing 3rd column

array([  3,  18, 128])

In [37]:
arr_2d[1:,1:]

array([[ 15,  18],
       [ 96, 128]])

In [38]:
arr_2d[1,1]

15

In [39]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 2,  3],
       [15, 18]])

## Indexing

In [40]:
import numpy as np

In [41]:
arr1=np.ones((5,10))
arr1



array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [42]:
arr1.shape

(5, 10)

In [43]:
#Set up matrix
arr2d = np.zeros((5,10))  # taking shape from an existing array

In [44]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
arr2d.shape

(5, 10)

In [46]:
arr2d.shape

(5, 10)

In [47]:
no_of_rows=arr2d.shape[1]  # indexing the shape tuple
no_of_rows

10

In [48]:
#Set up array

for i in range(5):
    arr2d[i] = i +10
    
arr2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

## Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

Fancy indexing allows the following

In [49]:
arr2d

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.]])

In [50]:
arr2d[[2,1,4,0]]

array([[12., 12., 12., 12., 12., 12., 12., 12., 12., 12.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [14., 14., 14., 14., 14., 14., 14., 14., 14., 14.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [51]:
arr2d[:,[2,4,0,0,0,0,0,0]]

array([[10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12.],
       [13., 13., 13., 13., 13., 13., 13., 13.],
       [14., 14., 14., 14., 14., 14., 14., 14.]])

In [52]:
#Allows in any order
arr2d[[1,4,2,0],2:4]

array([[11., 11.],
       [14., 14.],
       [12., 12.],
       [10., 10.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [53]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [55]:
arr[arr < 4]

array([1, 2, 3])

In [26]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [39]:
a=arr2d[:,0]
a[a<4]

array([0., 1., 2., 3.])

# Happy Learning!